// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIae783CfmEOG-9LyWJ-NT7dyeK-qsVM',
    appId: '1:927486835176:web:4a91ffbbf45ed427ab0c5d',
    messagingSenderId: '927486835176',
    projectId: 'travel-app-551de',
    authDomain: 'travel-app-551de.firebaseapp.com',
    storageBucket: 'travel-app-551de.firebasestorage.app',
    measurementId: 'G-ZXT7MCKRFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOHTdfOlp6vcvogr89eOWpylG3pToAMXs',
    appId: '1:927486835176:android:a7e20ec9addf0083ab0c5d',
    messagingSenderId: '927486835176',
    projectId: 'travel-app-551de',
    storageBucket: 'travel-app-551de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXZvYyBKaPxX9f9q8_zWlBH2MD29YR0qM',
    appId: '1:927486835176:ios:bc9f94aa680834f7ab0c5d',
    messagingSenderId: '927486835176',
    projectId: 'travel-app-551de',
    storageBucket: 'travel-app-551de.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXZvYyBKaPxX9f9q8_zWlBH2MD29YR0qM',
    appId: '1:927486835176:ios:bc9f94aa680834f7ab0c5d',
    messagingSenderId: '927486835176',
    projectId: 'travel-app-551de',
    storageBucket: 'travel-app-551de.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIIae783CfmEOG-9LyWJ-NT7dyeK-qsVM',
    appId: '1:927486835176:web:68887548eec2209cab0c5d',
    messagingSenderId: '927486835176',
    projectId: 'travel-app-551de',
    authDomain: 'travel-app-551de.firebaseapp.com',
    storageBucket: 'travel-app-551de.firebasestorage.app',
    measurementId: 'G-K3D6BRTSRL',
  );
}
